### ISSUE TITLE
Can't store string at smart contract

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [ethjs/ethjs#13]
When I pass string to the smartcontract method, it says :
```
Error: [ethjs-abi] invalid hex or buffer, must be a prefixed alphanumeric even length hex string
    at hexOrBuffer (index.js:41)
    at Object.encodeFixedBytes [as encode] (index.js:144)
    at eval (index.js:27)
    at Array.forEach (<anonymous>)
```

**Comment by SilentCicero** [comment]
Can you provide more code, and more about the contract (if not a snippet from the contract itself).

**Comment by vitaliy-kuzmich** [comment]
Contract method signature:
`function addTeam(bytes32 _sportType, bytes32 _teamName, bytes32 _description, bytes32 _externalId) public isOwner {`

TS calling code:
 ```
 async addNewTeam(team: Team) {
    //bytes32 _sportType, bytes32 _teamName, bytes32 _description, bytes32 _externalId)
    // this.logger.info(this.constructor.name, "ADDING new team")
    //console.dir(team)
    let result = await this.sportBetContract.addTeam(
      team.sportType,
      team.teamName,
      team.description,
      team.externalId, {
      gas: 6712390,
      from: this.accs[0].address
    });
    this.logger.info(this.constructor.name, "Add new team TX " + result)

  }
```

**Comment by SilentCicero** [comment]
I don't see a string type there? Are you trying to store strings as bytes32?

If so, those must be converted to hex.

Something like:

const hex = '0x' + Eth.Buffer(stringVal, 'utf8').toString('hex');

**Comment by vitaliy-kuzmich** [comment]
thank you @SilentCicero, this approach should be mention at the examples. PS In web3 it does  conversion automatically.
