### ISSUE TITLE
How do you add an account?

### ISSUE THREAD

**Issue by kingjerod** [ethjs/ethjs#26]
## Issue Type

- [ ] Bug (https://github.com/ethjs/ethjs/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [x] Feature

## Description

Add some documentation on how to add a private key or HD wallet to eth instance. 

## Steps to reproduce

There doesn't seem to be any sort of accounts or wallet available on the eth object. The docs only mention going to look at the other packages like ethjs-accounts, then going there doesn't show how it interacts with ethjs. All documentation just leaves out any mention of how to add an account. 

# Versions

- Node/NPM: 8.9
- ethjs: 0.3.3

**Comment by SilentCicero** [comment]
Will provide full answer tomorrow, but in essence, you should leave accounts to be handled by highly scrutinized code based and individuals (ie MetaMask or some other wallet) and not by the dapp developer.

But if your talking about just accessing accounts, they are provided by the Provider. If your using MetaMask than it is injected via window.web3.currentProvider, then just call eth_accounts (eth.accounts). Then to send a transaction as those accounts use (eth.sendTransaction with the from addressed specified as one provided by the provider).

**Comment by kingjerod** [comment]
I'm not writing a dapp, trying to write a back end API, so not using Metamask or any of those browser wallets. Maybe ethjs is not the right tool for the job.

**Comment by SilentCicero** [comment]
So you can use the ethjs-account module to generate accounts and ethjs-signer for signing transactions (however the signing module is not eip155 compliant). So I would recommend using either Ethereumjs-tx or ethers.js (full wallet + web3).
