### ISSUE TITLE
ethjs-contract out of date

### ISSUE THREAD

**Issue by treyhuffine** [ethjs/ethjs#27]
The [ethjs-contract](https://github.com/ethjs/ethjs-contract) was upgraded to 0.2.x.

Example of things that are broken: eth.contract(...).new() returns `undefined` instead of a promise if no callback is given.

Current workaround is to use the child libraries directly.

**Comment by SilentCicero** [comment]
A large update is coming to the main Ethjs library, we have just been
testing at the lower level modules first before moving them up to the main
lib.

**Comment by treyhuffine** [comment]
Thank you!

**Comment by treyhuffine** [comment]
@SilentCicero Just curious, but do you have a timeline when the update will happen?

**Comment by SilentCicero** [comment]
Hi! We have been bogged down by some other stuff over the past two weeks, totally my bad! I'm gonna do a bunch of merges tonight, fuck it!

**Comment by treyhuffine** [comment]
Going live! Thanks

**Comment by SilentCicero** [comment]
Check it out now, let me know your feedback and thoughts

**Comment by treyhuffine** [comment]
awesome, going to start using it right now

**Comment by treyhuffine** [comment]
It's still picking up the 0.1.9 release of `ethjs-contract`. Since the 1.0.0 hasn't been released, the `^` restricts it to only upgrading within the same patch release.

<img width="315" alt="screen shot 2018-05-09 at 5 44 35 pm" src="https://user-images.githubusercontent.com/11709986/39841497-ecc1c32c-53b0-11e8-92a7-72a42bf08d5b.png">

**Comment by SilentCicero** [comment]
Patching now. Thanks

**Comment by SilentCicero** [comment]
Is it addressed?

**Comment by treyhuffine** [comment]
Yep, it looks good to me. Thanks for the help @SilentCicero
