### ISSUE TITLE
[Feature] Static or CDN version.

### ISSUE THREAD

**Issue by KenoLeon** [ethjs/ethjs#9]
Started working with ethjs recently and one of the pain points was including it for online examples, 
( had to use the one from one of the sample files) and couldn't make one with browserify. It also feels like this should be included front and center since  your landing page states "Only 103 kB minified!" 

Thanks

**Comment by SilentCicero** [comment]
We should totally push this to a CDN, do you have any in mind?

**Comment by mateodelnorte** [comment]
https://cdnjs.com/ hosts lots of oss libs

**Comment by KenoLeon** [comment]
@SilentCicero +1 on cdnjs although they make you go through some loops:
https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md

In all honesty I would settle for a sanctioned ethjs-min.js somewhere in the repo I can include in projects.

**Comment by monokh** [comment]
[JsDelivr](https://www.jsdelivr.com/) automatically provides a CDN link for github projects. I've been using this path for testing codepens etc. https://cdn.jsdelivr.net/npm/ethjs@0.3.0/dist/ethjs.min.js

I'm not sure this is endorsed by the maintainer or not. Could include it in the readme but I imagine you would want to be sure of security standards of this CDN beforehand

**Comment by SilentCicero** [comment]
@monokh I'll include this in the readme, thanks!
